### ISSUE TITLE
Pipeline failing in Exercise 4 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-ML-Ops#13]
In Exercise 4 task 2, When we run the build pipeline it is getting failed 
![image](https://user-images.githubusercontent.com/57964598/70521734-c476fa80-1b65-11ea-8588-5878f1edaf27.png)

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  

We will review your issue soon.

Tim

**Comment by ciprianjichici** [comment]
I was unable to reproduce the problem. Can you please provide the detailed log of the Master Pipeline step so we can have a better understanding of the root cause? Thank you.

**Comment by himanshuahlawat31** [comment]
Hi , that issue is solved but we are getting failure in Exercise 6 task 3 
![image](https://user-images.githubusercontent.com/57964598/70625506-88689600-1c48-11ea-875b-378956b5f600.png)
[ReleaseLogs_1.zip](https://github.com/microsoft/MCW-ML-Ops/files/3950563/ReleaseLogs_1.zip)

**Comment by timahenning** [comment]
@himanshuahlawat31 If the original issue is solved, please open a new issue with so we can start tracking it.  Is this failure directly linked to the previous issue?
