### ISSUE TITLE
error in exercise 6 task 3

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-ML-Ops#14]
we are getting failure while running pipeline  in Exercise 6 task 3

![image](https://user-images.githubusercontent.com/57964598/70625506-88689600-1c48-11ea-875b-378956b5f600.png)
[ReleaseLogs_1.zip](https://github.com/microsoft/MCW-ML-Ops/files/3975315/ReleaseLogs_1.zip)

**Comment by shirolkar** [comment]
Hi @himanshuahlawat31 @timahenning 
Can you please review your setup in 
Task 7 / Step 3
Expand Advanced and provide Working Directory: $(System.DefaultWorkingDirectory)/_mlops-quickstart/devops-for-ai
This path works if your Azure DevOps project name is **mlops-quickstart** in Task 1 / Step 3. If you named your project something different (**mcw-mlops-starter**), you can set your path by selecting **Browse Working Directory** and then select the folder **devops-for-ai** as shown in the images below.
Please confirm this helps.
![image1](https://user-images.githubusercontent.com/18037946/71109570-767c7b00-2193-11ea-8ed2-610e56e04a23.png)
![image2](https://user-images.githubusercontent.com/18037946/71109576-7c725c00-2193-11ea-8a47-fe20ad1b5fd6.png)

**Comment by himanshuahlawat31** [comment]
will check and update you about the issue

**Comment by timahenning** [comment]
Closing this issue due to the lack of activity.  Please us know if this is still a problem and we will reopen the issue.
