### ISSUE TITLE
Azure Devops issue : not able to import repository 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-ML-Ops#16]
In exercise 3 task 2 https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20MLOps.md#task-2-import-quickstart-code-from-a-github-repo
while importing repository we are facing an issue 
![image](https://user-images.githubusercontent.com/57964598/71821175-6b907880-30b7-11ea-92b9-698320f7b8ff.png)
Workaround for the problem is  : 
1. Go to Account settings and Select “Preview Features“
2. Turn off “New Repos landing pages” preview feature.

In exercise 3 Task 4 step 3  https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20MLOps.md#task-4-create-new-service-connection
we are not getting option to select Service principal (automatic) feature, so we had to skip that step and we were able to test lab successfully

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #17.  Thank you!
