### ISSUE TITLE
Build Pipeline Error - Exercise 4

### ISSUE THREAD

**Issue by nfmoore** [microsoft/MCW-ML-Ops#20]
Hi everyone,

I'd like to bring an error to your attention in this workshop during [Exercise 4](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md#exercise-4-setup-and-run-the-build-pipeline). In this step you execute a build pipeline from the repo linked in the instructions. The code here does not have any issues from what I can see. The build pipeline is [here ](https://github.com/solliancenet/mcw-mlops-starter-v2/blob/master/azure-pipelines.yml#L52)for reference and fails at this [line](https://github.com/solliancenet/mcw-mlops-starter-v2/blob/master/aml_service/pipelines_master.py#L125).
 
This is the error message:
 
```
Traceback (most recent call last): 
File "aml_service/pipelines_master.py", line 125, in <module> 
pipeline_run.wait_for_completion(show_output=True) 
File "/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/lib/python3.6/site-packages/azureml/pipeline/core/run.py", line 291, in wait_for_completion 
raise_on_error=raise_on_error) 
TypeError: wait_for_completion() got an unexpected keyword argument 'timeout_seconds' 

```

Any ideas on a fix?

**Comment by nfmoore** [comment]
Solved this. The problem was resolved after using version 1.2.0 of the azureml library. Changes should be made to `install_requirements.sh` [here](https://github.com/solliancenet/mcw-mlops-starter-v2/blob/master/environment_setup/install_requirements.sh#L3) to specify the dependency version.

**Comment by timahenning** [comment]
Hi nfmoore,

We are going to have a look into this issue.

Tim

**Comment by shirolkar** [comment]
@nfmoore @timahenning This issue is fixed. Please pickup the latest changes from https://github.com/solliancenet/mcw-mlops-starter-v2.
