### ISSUE TITLE
Not able to select service connection quick-starts-sc

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-ML-Ops#21]
In exercise 5 task 7 we have to select **quick-start-sc** as a service connection , but i am not able to select the service connection that i created in previous exercise (quick-starts-sc)
![image](https://user-images.githubusercontent.com/57964598/83980569-869c3880-a934-11ea-9017-252ed6943a69.png)

**Comment by shirolkar** [comment]
@himanshuahlawat31 @timahenning 
Please select Task version as 1* and then you should be able to select your service connection. The instructions will be updated in the June 2020 update to make it clear. Thanks.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #23
