### ISSUE TITLE
Deep Learning with Text.ipynb doesn't work.

### ISSUE THREAD

**Issue by Sup90** [microsoft/MCW-ML-Ops#22]
Deep Learning with Text.ipynb doesn't work.

where line 176, **converted_model = onnxmltools.convert_keras(model, onnx_model_name, target_opset=7)**

with error('tuple' object has no attribute 'layer')

i think because of keras or tensorflow version update.

**Comment by shirolkar** [comment]
@timahenning @roxanagoidaci 
I might have fixed this issue as part of test/fix for this MCW. I was about to send the PR.

**Comment by gitsathish** [comment]
Issue with the same notebook, get this on the import statements in the notebook.
--------------------- Error ------------------------
Using TensorFlow backend.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-37-d955de91cd14> in <module>
     18 from azureml.train.dnn import TensorFlow
     19 
---> 20 from keras.models import load_model
     21 from keras.preprocessing.text import Tokenizer
     22 from keras.preprocessing.sequence import pad_sequences

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/utils/__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/utils/conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/backend/__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/backend/load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in <module>
     54 get_graph = tf_keras_backend.get_graph
     55 # learning_phase_scope = tf_keras_backend.learning_phase_scope  # TODO
---> 56 name_scope = tf.name_scope
     57 
     58 

AttributeError: module 'tensorflow' has no attribute 'name_scope'

**Comment by shirolkar** [comment]
@gitsathish @timahenning 
One other questions(1) when did you create your Azure compute instance to run the lab? 
Also, it may make sense to create a new issue since this is different that the one originally reported here. Thanks.

**Comment by gitsathish** [comment]
will create another case @shirolkar 
using compute instance created 1hour ago.
I get error below when I run, 
import keras
import tensorflow
print(keras.version)
print(tensorflow.version)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-09d02ef28c5b> in <module>
----> 1 import keras
      2 import tensorflow
      3 print(keras.version)
      4 print(tensorflow.version)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/utils/__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/utils/conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/backend/__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/backend/load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in <module>
     54 get_graph = tf_keras_backend.get_graph
     55 # learning_phase_scope = tf_keras_backend.learning_phase_scope  # TODO
---> 56 name_scope = tf.name_scope
     57 
     58 

AttributeError: module 'tensorflow' has no attribute '

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #23
