### ISSUE TITLE
Deep Learning with Text.ipynb

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-ML-Ops#25]
while running the experiment in Deep Learning with text.ipynb i am getting error as:
![image](https://user-images.githubusercontent.com/57964598/84182697-6b523a00-aaa8-11ea-9f83-87daa6385a9f.png)

**Comment by shirolkar** [comment]
Hi @himanshuahlawat31 Can you share the error from the driver_log.txt file. You can choose the diver_log file from the dropdown box Output Logs. Thanks.

**Comment by himanshuahlawat31** [comment]
yes please find the driver_log.txt file 
[driver_log.txt](https://github.com/microsoft/MCW-ML-Ops/files/4754717/driver_log.txt)

**Comment by shirolkar** [comment]
@himanshuahlawat31 
I fixed a similar issue today. You can find the new notebook at https://github.com/shirolkar/MCW-ML-Ops/tree/master/Hands-on%20lab/notebooks
Would you be able to use this notebook?
I have sent a PR to Microsoft to accept this change.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #23
