### ISSUE TITLE
Not able to select Service connection 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-ML-Ops#26]
In exercise 3 task 4 step 3 i am not able to select machine learning workspace even though workspace is created 
![image](https://user-images.githubusercontent.com/57964598/84190031-dbb28880-aab3-11ea-80ac-188a5412518d.png)

**Comment by shirolkar** [comment]
@himanshuahlawat31 This is odd. It was working couple of weeks back when I tested the lab. Can you try to change it to Subscription scope and pick your resource group.

**Comment by himanshuahlawat31** [comment]
i tried changing scope to resource group also , i am getting this error
![image](https://user-images.githubusercontent.com/57964598/84196246-93986380-aabd-11ea-886a-e45ae8e9ad4b.png)

**Comment by shirolkar** [comment]
@himanshuahlawat31 
Hi Himanshu - I also saw the above error. I existed the editor. refreshed my browser. Next time it worked - resource group level. Its very odd. Can you try again. Thanks.

**Comment by shirolkar** [comment]
@himanshuahlawat31 
I have updated the instructions to workaround the issue when you are unable to select your workspace. https://github.com/shirolkar/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md

**Comment by himanshuahlawat31** [comment]
@shirolkar I tried with updated instruction but the issue is same

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #23
