### ISSUE TITLE
Having an issues during task 4: Mastering pipeline

### ISSUE THREAD

**Issue by anderhong** [microsoft/MCW-ML-Ops#27]
Tried so many times and the job stopped facing: "'Run' object has no attribute 'get_output_data'",

	Message: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "User program failed with AttributeError: 'Run' object has no attribute 'get_output_data'",
        "detailsUri": "https://aka.ms/azureml-known-errors",
        "details": [],
        "debugInfo": {
            "type": "AttributeError",
            "message": "'Run' object has no attribute 'get_output_data'",
            "stackTrace": "  File \"azureml-setup/context_manager_injector.py\", line 148, in execute_with_context\n    runpy.run_path(sys.argv[0], globals(), run_name=\"__main__\")\n  File \"/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/lib/python3.6/runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n  File \"/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"aml_service/pipelines_master.py\", line 130, in <module>\n    data = pipeline_run.find_step_run('evaluate')[0].get_output_data('evaluate_output')\n"
        },
        "messageParameters": {}
    },

{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with AttributeError: 'Run' object has no attribute 'get_output_data'\",\n        \"detailsUri\": \"https://aka.ms/azureml-known-errors\",\n        \"details\": [],\n        \"debugInfo\": {\n            \"type\": \"AttributeError\",\n            \"message\": \"'Run' object has no attribute 'get_output_data'\",\n            \"stackTrace\": \"  File \\\"azureml-setup/context_manager_injector.py\\\", line 148, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"aml_service/pipelines_master.py\\\", line 130, in <module>\\n    data = pipeline_run.find_step_run('evaluate')[0].get_output_data('evaluate_output')\\n\"\n        },\n        \"messageParameters\": {}\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}"
    }
}
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1
/opt/hostedtoolcache/Python/3.6.11/x64/bin/az account clear
[error.txt](https://github.com/microsoft/MCW-ML-Ops/files/4945594/error.txt)

**Comment by shirolkar** [comment]
@anderhong @timahenning 
Hi Guys - I just tested this in a new env and I cannot reproduce this issue. Can you please check the version of Azure ML SDK used during the master pipeline run. When I ran this today, the version was 1.10.0. Thanks.

In piplines_master.py
Pipeline SDK-specific imports completed
Azure ML SDK version: 1.10.0

**Comment by anderhong** [comment]
Hi @shirolkar .  yes, the error fixed by update the Azure ML SDL 1.10.0 on install_requirements.sh and pipelines_master.py
