### ISSUE TITLE
Azure ML compute name should be unique in whole Azure region

### ISSUE THREAD

**Issue by rgknp** [microsoft/MCW-ML-Ops#28]
Task 1 -> Step 10 in HOL has this:

a. Compute name: mlops-compute. When you create a VM, provide a name. The name must be between 2 to 16 characters. Valid characters are letters, digits, and the - character, and **must also be unique across your Azure subscription**.

However when I create the AML compute it fails with below error:

"Compute with this name already exists. Compute name needs to be unique across all existing computes within an Azure region."

This means that AML compute name has to be unique across entire Azure Region instead of just subscription. 
You can ask users to suffix a unique identifier to their AML compute name.

**Comment by shirolkar** [comment]
@rgknp @DawnmarieDesJardins @timahenning 
This issue is not a showstopper issue. We will address this issue in the upcoming Sept 2020 update. Thanks. Jitendra

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #36
