### ISSUE TITLE
Application Insights telemetry data is not available

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-ML-Ops#3]
In step [Ex-8.2.7](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20MLOps.md#task-2-check-application-insights-telemetry),  there is no telemetry data present. I tried by running the whole lab 2 times.

**Comment by DawnmarieDesJardins** [comment]
Closing issue - address in latest merge.
