### ISSUE TITLE
"Can't import tf2onnx module ..." during keras conversion

### ISSUE THREAD

**Issue by alexanderv21** [microsoft/MCW-ML-Ops#32]
Hi,

Found some warning error like below during keras to onnx conversion:

> Saving model files...
model saved in ./outputs/model folder
Saving model files completed.
Can't import tf2onnx module, so the conversion on a model with any custom/lambda layer will fail!
WARNING - Can't import tf2onnx module, so the conversion on a model with any custom/lambda layer will fail!
Model exported in ONNX format...

![image](https://user-images.githubusercontent.com/17249308/92855183-38f40800-f41c-11ea-8256-4cf0e4181ebd.png)

Adding pip install of `tf2onnx` should fix the issue, for example:

> !pip install tf2onnx==1.6.3

Thanks!

#31

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #31
