### ISSUE TITLE
Lab failing during Release: failing at the step of creating webservices.

### ISSUE THREAD

**Issue by leeoommen** [microsoft/MCW-ML-Ops#33]
To the best of my knowledge I did follow the instructions and having failure towards the end of lab where it really matters. Build succeeded. During Release, failing at the step of creating webservices. devops does not provide anything much to troubleshoot this.

When I load the same image that was built using devops on ACI, I see this message.

“ModuleNotFoundError: No module named 'ruamel'
Worker exiting (pid: 41)”

May I request you please help me troubleshoot this and get the lab working.
I did not want to spin cycles troubleshooting the build process since it’s not my specialty (I specialize on Azure App/Infra and Devops). I would love to get this lab working as I see great value coming out of this for my customer team that mainly consist of data scientists who are struggling  to piece together container and devops aspect = MLOPS. Even if the webservice is failing its still valuable because I get the process / tasks sorted out. If this is not the right forum, I apologize and would appreciate if you could direct me to the right support group.

**Comment by shirolkar** [comment]
@leeoommen  @timahenning  @DawnmarieDesJardins I will take care of this during the October 2020 update. Thanks. Jitendra

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #36
