### ISSUE TITLE
Deploy and Test Webservice steps fails with different reasons

### ISSUE THREAD

**Issue by rgknp** [microsoft/MCW-ML-Ops#34]
Exercise 6: Test Build and Release Pipelines
Task 4: Review Release Pipeline Outputs

#1 Deploy and Test Webservice step fails with error "ServicePrincipalNotFound". See attached log tasklog_8.log
[tasklog_8.log](https://github.com/microsoft/MCW-ML-Ops/files/5285432/tasklog_8.log)

#2 Deleted failed AKS cluster (may be consider checking AKS provisioning state and add step to delete bad/failed clusters)

#3 Redeployed Release pipeline. This time AKS Cluster created successfully but it fails while creating AML Endpoint with error "CrashLoopBackOff" container is crashed. See attached tasklog_8 (1).log
[tasklog_8 (1).log](https://github.com/microsoft/MCW-ML-Ops/files/5285441/tasklog_8.1.log)

**Comment by shirolkar** [comment]
@timahenning @DawnmarieDesJardins @rgknp  I will take care of this during the October 2020 update. Thanks. Jitendra

**Comment by rgknp** [comment]
Hi @shirolkar can you pls share when October 2020 is planned to roll out? Also if it is a known issue can you pls share how to fix so I can be unblocked? I am running some Customer demos and if I can fix my setup that would be great. Thanks!

**Comment by shirolkar** [comment]
@rgknp its scheduled to be published 10/23. The change is non-trivial. If you prefer to you can do your demo from my fork which has the October updates: https://github.com/shirolkar/MCW-ML-Ops
Note that there are lot of changes in this update and the underlying source code repository is also different. All the instructions are updated on my fork.

**Comment by rgknp** [comment]
I pulled up the latest October 2020 changes from Master (it was updated yesterday). Rebuilt my repo from the new source, create a new build pipeline but it fails to build with follow error: 
Traceback (most recent call last):
  File "aml_service/pipelines_master.py", line 130, in <module>
    data = pipeline_run.find_step_run('evaluate')[0].get_output_data('evaluate_output')
AttributeError: 'Run' object has no attribute 'get_output_data'


Execution Summary
=================
RunId: quick-starts-mlops_1601503037_9e7c2c6d
Web View: https://ml.azure.com/experiments/quick-starts-mlops/runs/quick-starts-mlops_1601503037_9e7c2c6d?wsid=/subscriptions/93231767-b41d-4cbb-a2d3-2137400dfde2/resourcegroups/MCW-MLOps/workspaces/quick-start-ws
ActivityFailedException:
	Message: Activity Failed:
{
    "error": {
        "code": "ServiceError",
        "message": "Failed to run ['/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/bin/python', 'azureml-setup/run_script.py', '/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/bin/python', 'azureml-setup/context_manager_injector.py', '-i', 'ProjectPythonPath:context_managers.ProjectPythonPath', '-i', 'RunHistory:context_managers.RunHistory', '-i', 'TrackUserError:context_managers.TrackUserError', '-i', 'UserExceptions:context_managers.UserExceptions', 'aml_service/pipelines_master.py', '--aml_compute_target', 'amlcluster', '--model_name', 'compliance-classifier', '--build_number', '20200930.1', '--path', '/home/vsts/work/1/s'] \n Exit code 1 \nDetails can be found in azureml-logs/60_control_log.txt log file.",
        "details": [],
        "messageParameters": {}
    },
    "time": "0001-01-01T00:00:00.000Z"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"ServiceError\",\n        \"message\": \"Failed to run ['/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/bin/python', 'azureml-setup/run_script.py', '/home/vsts/.azureml/envs/azureml_162b9bd49e6546a5993481df5aa0d8e4/bin/python', 'azureml-setup/context_manager_injector.py', '-i', 'ProjectPythonPath:context_managers.ProjectPythonPath', '-i', 'RunHistory:context_managers.RunHistory', '-i', 'TrackUserError:context_managers.TrackUserError', '-i', 'UserExceptions:context_managers.UserExceptions', 'aml_service/pipelines_master.py', '--aml_compute_target', 'amlcluster', '--model_name', 'compliance-classifier', '--build_number', '20200930.1', '--path', '/home/vsts/work/1/s'] \\n Exit code 1 \\nDetails can be found in azureml-logs/60_control_log.txt log file.\",\n        \"details\": [],\n        \"messageParameters\": {}\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}"
    }
}
Logs attached:
[logs_10.zip](https://github.com/microsoft/MCW-ML-Ops/files/5308552/logs_10.zip)

**Comment by shirolkar** [comment]
@rgknp Thanks for finding this issue. The version of AML SDK changed from time I was making this update and there a change in behavior in AML SDK that is causing this issue. I would not be surprised if a future version of AML SDK fixes this issue without any change. I have found a workaround that I will test and put in today.

**Comment by shirolkar** [comment]
@rgknp I have committed my changes to workaround this issue. The changes are only in one file: https://github.com/solliancenet/mcw-mlops-starter-v3/blob/master/aml_service/pipelines_master.py
Thanks for finding this issue and please let me know if you run into other problems.

**Comment by rgknp** [comment]
Thanks. It worked! 
I am now able to deploy model to AKS and got back the endpoint. Will continue testing.

Thanks for the quick response!

**Comment by timahenning** [comment]
Issue resolved.
