### ISSUE TITLE
Pipeline failure in Exercise4

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-ML-Ops#37]
In Exercise4 Task2 (Run the Build Pipeline) step3,  the pipeline failed.
Please find the screenshots and log file of the pipeline below for reference.

![Screenshot (102)](https://user-images.githubusercontent.com/52440474/96266718-96174680-0fe4-11eb-9914-212a83e88b64.png)

Log file:
[1_Job (1).txt](https://github.com/microsoft/MCW-ML-Ops/files/5392065/1_Job.1.txt)

Can you please check on this.

Thanks,
Tejaswini

**Comment by ErnstRoell** [comment]
Got exactly the same error,  AttributeError: 'Run' object has no attribute 'get_output_data'.

With an earlier version of the code (20 May) that used to run correctly got an error on the the "wait_for_completion" with 
attribute error "timeout_seconds

**Comment by shirolkar** [comment]
@tejaswini972 @ErnstRoell 
There is an issue with the newer versions of AML Python SDK. This issue (AttributeError: 'Run' object has no attribute 'get_output_data'.) will be fixed as part of the October 2020 update. If you want an fix earlier. Here are two changes to do to fix this issue:

Get install_requirements.sh file from: https://github.com/solliancenet/mcw-mlops-starter-v3
(this first change is for yet another issue with azureml-sdk 1.16.0, so we pin the sdk to 1.15.0 for now)

In pipelines_master.py after the line pipeline_run.wait_for_completion(show_output=True, timeout_seconds=43200) make the following change:

print("Get StepRun for evaluate step...")
pipeline_run_id = pipeline_run.id
step_run_id = pipeline_run.find_step_run('evaluate')[0].id
node_id = pipeline_run.get_graph().node_name_dict['evaluate'][0].node_id
print('Pipeline Run ID: {} Step Run ID: {}, Step Run Node ID: {}'.format(pipeline_run_id, step_run_id, node_id))
step_run = StepRun(run.experiment, step_run_id, pipeline_run_id, node_id)
print(step_run)
print("Downloading evaluation results...")
# access the evaluate_output
#data = pipeline_run.find_step_run('evaluate')[0].get_output_data('evaluate_output')
data = step_run.get_output_data('evaluate_output')
# download the predictions to local path
data.download('.', show_progress=True)

the above code will replace the print("Downloading evaluation results...") section. Again you can find this part of the code in: https://github.com/solliancenet/mcw-mlops-starter-v3.

Hope this help.

Jitendra

**Comment by akn9050** [comment]
Hi @shirolkar,
 thanks for the update, we will check this out and let you know.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #36
