### ISSUE TITLE
experiment failing in exercise 1 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-ML-Ops#38]
While running experiment in deep learning with text , experiment is getting failed 
please find the logs file
[70_driver_log.txt](https://github.com/microsoft/MCW-ML-Ops/files/5490515/70_driver_log.txt)

**Comment by himanshuahlawat31** [comment]
Adding to the below : 

In exercise 6 task 4 release pipeline is failing ,please find the logs 
 
[tasklog_8.log](https://github.com/microsoft/MCW-ML-Ops/files/5491228/tasklog_8.log)

**Comment by shirolkar** [comment]
@himanshuahlawat31 @timahenning @DawnmarieDesJardins 
This issue is new because of changes in the default AML compute image and this issue now fixed in the Oct 2020 update. So when we merge the PR it should address this issue.

**Comment by Barkha** [comment]
I ran this this am am still seeing it.

**Comment by shirolkar** [comment]
@Barkha The PR is not merged. The latest updates to the MCW that will be merged soon can be found at: https://github.com/shirolkar/MCW-ML-Ops

**Comment by himanshuahlawat31** [comment]
@timahenning @DawnmarieDesJardins @shirolkar when do we expect the PR to merge as we have labs scheduled

**Comment by Barkha** [comment]
Now getting a new error on load_model 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-66-19a63fa35a6e> in <module>
      1 from keras.models import load_model
----> 2 model = load_model('./model/model.h5')
      3 print("Model loaded from disk.")
      4 print(model.summary())

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/engine/saving.py in load_wrapper(*args, **kwargs)
    490                 os.remove(tmp_filepath)
    491             return res
--> 492         return load_function(*args, **kwargs)
    493 
    494     return load_wrapper

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/engine/saving.py in load_model(filepath, custom_objects, compile)
    582     if H5Dict.is_supported_type(filepath):
    583         with H5Dict(filepath, mode='r') as h5dict:
--> 584             model = _deserialize_model(h5dict, custom_objects, compile)
    585     elif hasattr(filepath, 'write') and callable(filepath.write):
    586         def load_function(h5file):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/engine/saving.py in _deserialize_model(h5dict, custom_objects, compile)
    271     if model_config is None:
    272         raise ValueError('No model found in config.')
--> 273     model_config = json.loads(model_config.decode('utf-8'))
    274     model = model_from_config(model_config, custom_objects=custom_objects)
    275     model_weights_group = h5dict['model_weights']

AttributeError: 'str' object has no attribute 'decode'

**Comment by timahenning** [comment]
@himanshuahlawat31 Our goal is to merge it some time today.

**Comment by himanshuahlawat31** [comment]
Thanks for the update

**Comment by shirolkar** [comment]
@Barkha 
The version of tensorflow changed on new compute instances. Please pickup the latest notebook from the fork for the fix:
https://github.com/shirolkar/MCW-ML-Ops/blob/master/Hands-on%20lab/notebooks/Deep%20Learning%20with%20Text.ipynb

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #36
