### ISSUE TITLE
Pipeline Run failed when it tried to install the CLI

### ISSUE THREAD

**Issue by jhasanjay** [microsoft/MCW-ML-Ops#4]
ERROR: command authoring error for 'account set': 'subscription' conflicting option string: --subscription

**Comment by timahenning** [comment]
Thank you for bringing this to our attention.  We will look into it.

Tim

**Comment by shirolkar** [comment]
Hi @jhasanjay can you check the version of azure CLI installed from environment_setup/install_requirements.sh. If it says, azure-cli==2.0.46, can you change that to azure-cli==2.0.49 and see if it fixes your issue.

**Comment by jhasanjay** [comment]
Thanks for quick response.. I put cli=2.0.69 and then it worked.
