### ISSUE TITLE
Issues in Labguide 

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-ML-Ops#43]
### Please find the few upadtion suggestions below:
1. Required DevOps agent to complete the lab (paid), whereas in requirement it's asked to use a free Azure DevOps subscription. 
2. Exercise 1, Task 1, step 10 > Screenshot requires updation (AML UI changed)
3. Exercise 1, Task 1, step 11 > Instructions to **Authenticate** is missing, and also not able to find the edit option as per the    instruction/ screenshot
4.  Exercise 1, Task 2 , Step 1> While running the notebooks came across instructions to provide `subscription_id`, `resource_group` , `workspace_name` and `workspace_region` in the cells, but not able to identify which cell to be update with these values.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #44
