### ISSUE TITLE
Facing Error while building a Pipeline in Azure DevOps.

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-ML-Ops#45]
In Exercise 4 - Task 2, While building a pipeline in Azure DevOps facing an error-
There was a resource authorization issue: "The pipeline is not valid. Could not find a pool with name Hosted Agent. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz." 
Even after authorizing resources and Agent Pool is available with online status, but pipeline build is getting failed.
Kindly refer the below attached screenshot :
![image](https://user-images.githubusercontent.com/83394010/126315762-98b2c457-34a4-4536-91ce-234f43d168c1.png)

**Comment by shirolkar** [comment]
@Karthikkc123 Did you create a Self-Hosted Agent Pool as per https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md#task-2-setup-self-hosted-agent-pool. Also, when you created the Agent Pool, did you enable Auto-provision this agent pool in all projects? You also need to get the latest code from https://github.com/solliancenet/mcw-mlops-starter-v3. Please confirm. @timahenning

**Comment by Karthikkc123** [comment]
@shirolkar I have followed all the above mentioned steps but also I'm unable to build the pipeline.

**Comment by timahenning** [comment]
@Karthikkc123 Did MS approve your pipelines?

**Comment by Karthikkc123** [comment]
@timahenning No, MS did not approve our pipelines.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #49
