### ISSUE TITLE
Issue in Before the hands-on lab, excerise- 1, task- 2

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-ML-Ops#47]
In step- 1, I'm getting an error while running the notebook where we install libraries for Azure ML.

Code cell:
![image](https://user-images.githubusercontent.com/81952290/127993037-e76b43bb-37dc-43df-817c-72e5f00ce1a2.png)

Error:
![image](https://user-images.githubusercontent.com/81952290/127993168-fa4b02eb-6317-4dec-b72a-16a7ea7abd7c.png)
![image](https://user-images.githubusercontent.com/81952290/127993190-7a183b07-440d-4a52-adae-3a52bb88b5a7.png)

**Comment by shirolkar** [comment]
@Shivashant25 I believe you are working with an older version of the notebook. The lab files were updated recently. Please use the latest version of the notebook. Thanks. Jitendra @timahenning  @DawnmarieDesJardins

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further communication received.  Please feel free to reopen if you're still having trouble.
