### ISSUE TITLE
lab Guide Updates

### ISSUE THREAD

**Issue by Kalyani7744** [microsoft/MCW-ML-Ops#51]
1. [Before hands on lab, task 4, Step 14](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20MLOps.md) While running the linux commands, **tar zxvf ../vsts-agent-linux-x64-2.191.1.tar.gz** command will throw an error as the downloaded agent version will differ from the given one. Instruction has be added regarding it.

2. [Before hands on lab, task 4, Step 5](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20MLOps.md) Users will not be able to add the agent pool without creating project. 
Instructions has to be added for creating the project in before hands on lab.

3. [Exercise 1, task 4, step 3](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md#task-4-create-new-service-connection) The UI for creating the Service connection is updated as shown below. Screenshot has to be updated.

![Git1](https://user-images.githubusercontent.com/83349665/135028263-e8bf3c66-19b1-46b0-b9c2-c2f42bebdfec.png)

4. [Exercise 3, task 4, step 2](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md#task-4-create-new-service-connection) While filling the details in Azure CLI, **Azure Resource manger connection** option is there after display name, but in options it is mentioned as Azure Subscription.

Instruction has to be updated.

![Git2](https://user-images.githubusercontent.com/83349665/135029264-e7348c17-1240-4ba2-987f-b25fb855deb4.png)

5. [Exercise 3](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md#task-4-create-new-service-connection) After adding Azure CLI and Azure ML  model deploy to the agent job, there will be 1 job and 2 tasks as shown below. But in Exercise 3 screenshots there is mentioned as 1 job and 1 task.

screenshots has to be updated as shown below.

![Git3](https://user-images.githubusercontent.com/83349665/135030701-1ab8e974-8871-4229-b189-94f528fbde67.png)

6. [Exercise 7, task 2 , step 6](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md#task-4-create-new-service-connection) for checking logs in application insights, when i hover over request table, I cannot see the eyeball icon as shown in lab guide screenshot.

Screenshot has to be updated as below.

![Git5](https://user-images.githubusercontent.com/83349665/135031169-edd06ad5-b8ef-4bb4-87e9-41b7f369cf4d.png)

7. [Exercise 7, task 3, step 3](https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20MLOps.md#task-4-create-new-service-connection) For viewing the model data users are requested to click on **Storage Explorer**. But the UI for storage account is updated and the option is changed to **Storage browser(Preview)** as shown in below screenshot.

Screenshot and instruction has to be updated

![Git4](https://user-images.githubusercontent.com/83349665/135031484-d0eaa2a5-6ff1-4cec-86ba-02b48ca1979a.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #52
