### ISSUE TITLE
November 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-ML-Ops#7]
This workshop is scheduled for a content update. Solliance, please review the workshop and provide your update suggestions for SME review here.

**Comment by ciprianjichici** [comment]
Here are some suggestions for the content update:

1. Whiteboard design student guide - include data versioning in the infographic for common scenarios
2. WDS trainer presentation - include data versioning in slide 9
3. Update screenshots to new AML user experience
4. Update screenshots to new Azure DevOps experience
5. Build pipeline - trace trained model back to source code and Azure DevOps build number
6. Build pipeline - snapshot training data on each pipeline run
7. Add support for creating the AML compute resource in the same region as the AML workspace (necessary in case the compute is not created by the time the pipeline runs)
8. Bring install_requirements.sh up to date (azure-cli version)

**Comment by ciprianjichici** [comment]
#11 has some great feedback we should incorporate as well in the changes:
9. Showcase the use of Azure DevOps ML extension
10. Showcase the use of ONNX (as it is referred in the WDS)
